version: "3.8"

services:
  hello-service:
    build:
      context: ./Sample-services/hello-service/HelloService
      dockerfile: Dockerfile
    ports:
      - "5074:8080" # Map the service's port to the host machine

  world-service:
    build:
      context: ./Sample-services/world-service/WorldService
      dockerfile: Dockerfile
    ports:
      - "5039:8080" # Map the service's port to the host machine
