on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      zap:
        image: owasp/zap2docker-stable
        ports:
          - 8090:8090
    steps:
<<<<<<< HEAD
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET Core SDK and Swashbuckle CLI
        run: |
          sudo apt-get install -y dotnet-sdk-6.5
          dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.5.0

      - name: Restore Dependencies and Build hello-service
=======
      - uses: actions/checkout@v2
      - name: Setup Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Install Java 18.0.2-ea
>>>>>>> cc0c8ef (modifications for zap testing)
        run: |
          sudo apt-get install -y openjdk-18-jdk
          java -version
      - name: Install python deps
        run: |
<<<<<<< HEAD
          cd ../../world-service/WorldService
          dotnet restore
          dotnet build
          dotnet swagger tofile --output swagger.json --outputFormat json world-service.csproj

  scans:
    runs-on: ubuntu-latest
    name: ZAP API Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly

      - name: Run ZAP Active Scan for hello-service
        run: |
          cd Sample-services/hello-service/HelloService
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py \
            -t http://localhost:5074/hello -r zap-report_hello_$(date -u +'%Y%m%d').html -c api-scan.conf

      - name: Run ZAP Active Scan for world-service
        run: |
          cd ../../world-service/WorldService
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py \
            -t http://localhost:5039/world -r zap-report_world_$(date -u +'%Y%m%d').html -c api-scan.conf

      - name: Complete Workflow
        run: |
          echo "Workflow Completed: ZAP CI Scan"


  deploy_reports:
    runs-on: ubuntu-latest
    needs: scans
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and Push Reports Branch
        run: |
          git checkout -b reports
          git add Sample-services/*/HelloService/zap-report_hello_* Sample-services/*/WorldService/zap-report_world_*
          git commit -m "Add ZAP scan reports"
          git push origin reports

=======
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4
      - name: Build Image
        run: docker-compose -f ./Sample-services/docker-compose.yml build
      - name: Run Docker Compose
        run: docker-compose -f ./Sample-services/docker-compose.yml up -d
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: "20s"
      - name: Run Test Automation with ZAP (zap-testing-world.py)
        run: |
          docker-compose -f ./Sample-services/docker-compose.yml exec zap python ./Sample-services/zap-testing-world.py
      - name: Run Test Automation with ZAP (zap-testing.py)
        run: |
          docker-compose -f ./Sample-services/docker-compose.yml exec zap python ./Sample-services/zap-testing.py
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: zap-scan-reports
          path: ./Sample-services/*.txt
>>>>>>> cc0c8ef (modifications for zap testing)
