name: Navigate to Deployment-definitions

on:
  push:
    branches:
      - main

jobs:
  navigate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'  

      - name: Navigate to Deployment-definitions
        run: cd ./Deployment-definitions && pwd && ls


