name: Build-push-docker-images

on:
  push:
    branches: [main]

jobs:
  build:
    name: For Hello Service
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: az login
        uses: azure/docker-login@v1
        with:
          login-server: debugdemoimage.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker build and push
        run: |
          cd Sample-services/world-service/WorldService
          docker build . -t hello-service
          docker tag hello-service:latest debugdemoimage.azurecr.io/hello-service:latest
          docker push debugdemoimage.azurecr.io/hello-service:latest

