name: Navigate to Deployment-definitions

on:
  push:
    branches:
      - main

jobs:
  navigate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to Deployment-definitions
        run: cd ./Deployment-definitions && pwd && ls


