name: Unit-Testing

on:
  push:
    branches: [main]

jobs:
  build:
    name: Unit Test Hello Service
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Change this to the desired .NET SDK version

      - name: Restore dependencies
        run: dotnet restore ./Sample-services/hello-service/HelloService.Tests

      - name: Run tests
        run: dotnet test ./Sample-services/hello-service/HelloService.Tests

  test-world-service:
    name: Unit Test World Service
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Change this to the desired .NET SDK version

      - name: Restore dependencies
        run: dotnet restore ./Sample-services/world-service/WorldService.Tests

      - name: Run tests
        run: dotnet test ./Sample-services/world-service/WorldService.Tests

