name: Navigate to Deployment-definitions and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Navigate to Deployment-definitions
        run: cd ./Deployment-definitions && pwd && ls

      - name: Navigate to Deployment-definitions
        run: |
          pwd && ls
          cd ./Deployment-definitions && pwd && ls
          az aks get-credentials --resource-group debug-demo --name debugdemocluster
          


