
name: ZAP CI Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Generate OpenAPI Specifications

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET Core SDK and Swashbuckle CLI
        run: |
          sudo apt-get install -y dotnet-sdk-8.0
          dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 7.0.0

      - name: Restore Dependencies and Build hello-service
        run: |
          cd Sample-services/hello-service/HelloService
          dotnet restore
          dotnet build
          dotnet swagger tofile --output swagger.json --outputFormat json hello-service.csproj

      - name: Restore Dependencies and Build world-service
        run: |
          cd ../../world-service/WorldService
          dotnet restore
          dotnet build
          dotnet swagger tofile --output swagger.json --outputFormat json world-service.csproj


  scans:
    runs-on: ubuntu-latest
    name: ZAP API Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly

      - name: Run ZAP Active Scan for hello-service
        run: |
          cd Sample-services/hello-service/HelloService
          sudo docker run -v $(pwd):/zap/wrk/:rw -t http://localhost:5074/hello -r zap-report_hello_$(date -u +'%Y%m%d').html -c api-scan.conf


      - name: Run ZAP Active Scan for world-service
        run: |
          cd ../../world-service/WorldService
          sudo docker run -v $(pwd):/zap/wrk/:rw -t http://localhost:5039/world -r zap-report_hello_$(date -u +'%Y%m%d').html -c api-scan.conf

      - name: Complete Workflow
        run: |
          echo "Workflow Completed: ZAP CI Scan"

  deploy_reports:
    runs-on: ubuntu-latest
    needs: scans
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and Push Reports Branch
        run: |
          git checkout -b reports
          git add Sample-services/*/HelloService/zap-report_hello_* Sample-services/*/WorldService/zap-report_world_*
          git commit -m "Add ZAP scan reports"
          git push origin reports
