on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      zap:
        image: owasp/zap2docker-stable
        ports:
          - 8090:8090
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Install Java 18.0.2-ea
        run: |
          sudo apt-get install -y openjdk-18-jdk
          java -version
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.4
      - name: Build Image
        run: docker-compose -f ./Sample-services/docker-compose.yml build
      - name: Run Docker Compose
        run: docker-compose -f ./Sample-services/docker-compose.yml up -d
      - name: Sleep for a bit
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: Run Test Automation with ZAP (zap-testing-world.py)
        run: |
          docker-compose -f ./Sample-services/docker-compose.yml exec zap python ./Sample-services/zap-testing-world.py
      - name: Run Test Automation with ZAP (zap-testing.py)
        run: |
          docker-compose -f ./Sample-services/docker-compose.yml exec zap python ./Sample-services/zap-testing.py
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: zap-scan-reports
          path: ./Sample-services/*.txt
