on: [push]

name: AKS deployment

jobs:
  Deploy-to-AKS:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - name: Deploying Services
        run: |
          find /home/runner/work/sample-services -type d -name "Deployment-definitions"
          pwd
          cd ./Deployment-definitions
          az aks get-credentials --resource-group debug-demo --name debugdemocluster
          kubectl get nodes
          az acr list --resource-group debug-demo --query "[].{acrLoginServer:loginServer}" --output table
          cd ./Deployment-definitions
          kubectl apply -f hello-deployment.yaml
          kubectl apply -f world-deployment.yaml
          kubectl get events
          kubectl get services

         

