name: ZAP CI Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Generate OpenAPI Specifications

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        run: |
          sudo apt-get install -y dotnet-sdk-7.0.x

      - name: Restore Dependencies and Build hello-service
        run: |
          dotnet restore hello-service/hello-service.csproj
          dotnet build hello-service/hello-service.csproj

      - name: Restore Dependencies and Build world-service
        run: |
          dotnet restore world-service/world-service.csproj
          dotnet build world-service/world-service.csproj

      - name: Generate OpenAPI Specifications for hello-service
        run: |
          dotnet swagger tofile --output hello-service/common-api-spec.json --outputFormat json hello-service/hello-service.csproj

      - name: Generate OpenAPI Specifications for world-service
        run: |
          dotnet swagger tofile --output world-service/common-api-spec.json --outputFormat json world-service/world-service.csproj

  scans:
    runs-on: ubuntu-latest
    name: ZAP API Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull ZAP OWASP Image
        run: docker pull owasp/zap2docker-weekly

      - name: Run ZAP Active Scan
        run: |
          sudo docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-full-scan.py \
            -t hello-service/common-api-spec.json -t world-service/common-api-spec.json \
            -f openapi -r zap-report_$(date -u +'%Y%m%d').html -c api-scan.conf
          echo "Workflow Completed: ZAP CI Scan"
